server:
  port: 8080

spring:
  application:
    name: repohealth-lite-plus

  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null